### ISSUE TITLE
ReferenceError: "window" is not defined (Using smarti.data with "Nashorn" JavaScript engine)

### ISSUE THREAD

**Issue by rognoni** [onitecsoft/smarti.data.js#2]
For my backends (Java/Node) I'm using **smarti.data**:

https://github.com/rognoni/adaptable/blob/master/Backend/Java-SpringBoot/src/main/java/io/github/rognoni/adaptable/JavaScript.java

``` java
    public static String[] scriptList = new String[] {
        "ext/lodash.min",
        "ext/smarti.data",
        "app",
        "controllers/storage",
        "storage/in_memory"
    };
```

but I see this error:

```
javax.script.ScriptException: ReferenceError: "window" is not defined in <eval> at line number 1
```

at the first line:

``` javascript
var smarti = window['smarti'] || {};
```

**Comment by onitecsoft** [comment]
Try:
`var smarti = this['smarti'] || {};`
or
`var smarti = global['smarti'] || {};`

I have updated src.
